package com.brijesh.expense_tracker.utils;

public enum Tags {
//    FIXED
    RENT, ELECTRICITY, INTERNET, COOK, CLEANER, DAIRY, FURNITURE_RENT,

//    VARIABLE
    PETROL, GROCERIES, ZOMATO_BLINKIT_BIGBASKER, CHAI_NASHTA, SHOPPING, DRY_FRUITS,

//    INVESTMENT
    SIP_LONG_TERM, SIP_SHORT_TERM,

//    INSURANCE
    TERM_LIFE,

//    MISCELLANEOUS
    TRAIN_TICKET, FLIGHT_TICKET, CYLINDER, GROOMING, URBAN_CLAP, SEND_ME, UDHAR

}
